### PR TITLE
Connections drawer

### PR DESCRIPTION
**Pull request by lrnt**
TODO:

- [x] Check if a connection is "launchable", if not redirect to the connection settings
- [x] Empty the transactions list when switching account (ideally with a warning)
- [x] Fix e2e tests
- [x] ~Remove settings page code~

### CODE REVIEW

**Comment by jfschwarz** [comment]
Super nice 👌 switching between connections feels very smooth now!

I have a couple small design feedback points:

- the bottommost connection is cut off in the scroll container:
image

- launch button could use more horizontal padding ("Add Connection" button has more, also would make it wider & a bit more prominent)
image

- connection items seem to be interactive (changing the border on hover), but I cannot click them (have to user the small connect/modify buttons)
- nit: the button is labeled "connect" in the list item view, "launch" in the details view

- would prefer if the connection pill in the top right would act as a single interactive unit: on hover it shows the current connection details, on click it opens the drawer
- this styling looks a a bit more harmonic to my eyes (just as a suggestion, I can also live with the current look of course)
image

**Comment by samepant** [comment]
@jfschwarz covered this feedback in #59

**Comment by jfschwarz** [comment]
>  Empty the transactions list when switching account (ideally with a warning)

We discussed storing recorded transactions in a more persistent way (local storage). With this in place, we might skip the warning. We store a transaction list per connection and switch between them when switching connections.

**Review by jfschwarz — APPROVED** [review]
pushed some small fixes and now feel this is merge-ready 🙌

**Review by samepant — APPROVED** [review]
made a couple small adjustments, looks good!!

**Pull request merged**
